In [1]:
!pip3 install torch

In [2]:
import torch

In [5]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [6]:
def forward(x):
  y = w*x + b
  return y

In [9]:
x = torch.tensor([[2], [7], [4]])
forward(x)

tensor([[ 7.],
        [22.],
        [13.]], grad_fn=<AddBackward0>)

In [10]:
from torch.nn import Linear

In [11]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)              

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [14]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)
