In [1]:
!pip3 install torch

In [2]:
import torch

In [3]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [4]:
def forward(x):
  y = w*x + b
  return y

In [5]:
x = torch.tensor([[2], [7], [4]])
forward(x)

tensor([[ 7.],
        [22.],
        [13.]], grad_fn=<AddBackward0>)

In [6]:
from torch.nn import Linear

In [7]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)              

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [8]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)


# Linear Regression Custom Modules 
## The complete PyToarh Course 
### Deep Learning & Computer Vision 

In [14]:
import torch.nn as nn
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    pred = self.linear(x)
    return pred


In [15]:
torch.manual_seed(1)
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [17]:
x = torch.tensor([[1.0], [2.0]])
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


# Linear Regression Creating Dataset 
## The complete PyToarh Course 
### Deep Learning & Computer Vision 