<a href="https://colab.research.google.com/github/desaiankitb/pytorch-basics/blob/main/deep-learning-blitz/00_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline

# Tensors
- Tensors are a specialized data structure that are very similar to array and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, we wll as model's parameters. 

- Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. If you are familiar with ndarrays, you will be right at home with the Tensor API. If not, follow along in this quick API walkthrough. 

In [2]:
import torch
import numpy as np 

Tensort Initialization 
-----------------------
 - Tensors can be initialized in various ways. Take a look at the following examples: 

**Directly from data**

- Tensors can be created directly from data. The data type is automatically inferrred. 



In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

- Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor**
- The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicity overridden. 

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand*10} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[3.7572, 7.7689],
        [3.1600, 9.2525]]) 



**With random constant values**
- `shape` is a tuple of tensor dimentions. In the functions below, it determines the dimensionality of the output tensor. 

In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8438, 0.9813, 0.4147],
        [0.5029, 0.9704, 0.0011]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor Attributes 
-----------------

- Tensor attributes describe their shape, datatype, and the device on which they are stored. 

In [8]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor Operations
-----------------
- Over 100 tensor operations, including transposing, indexing, slicing, methematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html)
- Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you are using Colab, allocate a GPU by going to Edit > Notebook Settings. 