<a href="https://colab.research.google.com/github/desaiankitb/pytorch-basics/blob/main/tutorial-pytorch-org/00_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

- Most machine learning workflows involve working with data, optimizing model parameters, and saving the training models. This module introduces you to a complete machine learning (ML) workflow implemented in PyTorch, a popular ML framework for Python. 

- We will use the FashionMNIST dataset to train a neural network that predicts if an input image belongs to one of the following classes: T-shirt/top, Trouser, Pullover, Dress, Coat, Sandal, Shirt, Sneaker, Bag, or Ankle boot. 

- Before we jump into building the model, you will learn a set of core concepts required to understand the basics of building Machine Learning models. Then the last step will put it all together. 

# Learning objectives

In this module you will: 

- Learn the key concepts used to build machine learning models 
- Learn how to build a Computer Vision model 
- Build models with the PyTorch API 

# Prerequisites
- Basic Python knowledge
- Basic knowledge about how to use Jupyter Notebooks 

<hr>

## Next unit: What are Tensors?

# What are Tensors?



In [ ]:
%matplotlib inline

## Tensors

- Tensors are specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters. 

- Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). Tensors are also optimized for automatic differentiation (we will see more about that later in the Autograd unit). If you are with `ndarrays`, you will be right at home with the Tensor API. If not, follow along!

- Let's start by setting up our environment. 

In [1]:
import torch
import numpy as np 

# Initializing a Tensor

- Tensors can be initialized in various ways. Take a look at the following examples:

## Directly from data

- Tensorts can be created directly from data. The data type is automatically inferred. 

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## From a NumPy array

- Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`). 

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## From another tensor: 

- The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatypes of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7054, 0.8765],
        [0.3637, 0.4355]]) 



##With random or constant values:

- `shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor. 

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7394, 0.9206, 0.8661],
        [0.7006, 0.7874, 0.7081]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor
- Tensor attributes describe their shape, data type, and the device on which they are stored. 

In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

- Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html). 

- Each of these operations can be run on the GPU (at typically higher speed than on a CPU). 

- By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using `.to` method (after checking for GPU availablity). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory! 

In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

- Try out some of the operations from the list. If you are familier with the NumPy API, you will find the Tensor API a breeze to use. 

## Standard numpy-like indexing and slicing:

In [10]:
tensor = torch.ones(4, 4)
print("First row", tensor[0])
print("First column", tensor[:, 0])
print("Last column", tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# Joining tensors

- You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining op that is subtly different from `torch.cat`. 

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)
print(tensor.shape)

torch.Size([4, 12])
torch.Size([4, 4])


## Airthmetic operations 

In [16]:
# This computes the matrix multiplication between two tensors. 
# y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. 
# z1, z2, z3 will have the same value 
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Single-element tensors
- If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place operations 
- Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example, `x.copy_(y)`, `x.t_()`, will change `x`. 

> **Note:** In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy
- Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other. 

### Tensor to NumPy array

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array. 

In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [22]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor. 

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
